name: RSS MD image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run RSS Feed to Markdown Action
        uses: keiranlovett/rss-feed-to-markdown@main
        with:
          feed_urls_file: 'feed_urls.json'
          feed_url: '${{ secrets.FEED_URL }}'
          template_file: 'assets/template.md'
          output_dir: '_posts/events/'
